---
abstract: 'DEPRECATED module for IDNA and Punyode'
author:
  - 'Claus Färber <CFAERBER@cpan.org>'
build_requires:
  Test::More: 0
  Test::NoWarnings: 0
configure_requires:
  Module::Build: 0.36
generated_by: 'Module::Build version 0.3624'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: IDNA-Punycode
provides:
  IDNA::Punycode:
    file: lib/IDNA/Punycode.pm
    version: 1.100
requires:
  Net::IDN::Nameprep: 1
  Net::IDN::Punycode: 1
resources:
  license: http://dev.perl.org/licenses/
version: 1.100
